# Tips and Tricks
## 1. Don't use rank one arrays

-  don't ( np.random.randn(5) )
-  do (np.random.randn(5, 1) or (1, 5) )

note: 
1. use asserstation statement to check the vectors
2. if we encounter the rank 1 arrays, we can reshape it a.reshape((5, 1) or (1, 5))


In [11]:
import numpy as np

a = np.random.randn(5)
# assert(a.shape == (5, 1))
print(a)
# rank 1 array

[-1.11277361 -0.76143782  0.18647204 -1.56163001 -0.46470962]


In [2]:
print(a.shape)

(5,)


note: This neither a row vector or a col vector, but its a rank 1 array

In [3]:
print(a.T)
# see we have same values for both a and a.T

[1.06686875 0.29572877 0.26851934 0.8398195  1.12611271]


In [5]:
print(np.dot(a, a.T))
# we hope we'll a  matrix rather it end up with a scalar value

3.2711937018678627


In [7]:
a = np.random.randn(5,1)
a
# a is col vector

array([[ 0.96215097],
       [-0.6595997 ],
       [-0.08830364],
       [ 1.36031449],
       [ 2.37769082]])

In [8]:
a.T
# a.T would be a row vector

array([[ 0.96215097, -0.6595997 , -0.08830364,  1.36031449,  2.37769082]])

In [9]:
print(np.dot(a, a.T))
# now we'll get a matrix

[[ 0.92573448 -0.63463449 -0.08496144  1.3088279   2.28769752]
 [-0.63463449  0.43507177  0.05824506 -0.89726303 -1.56832416]
 [-0.08496144  0.05824506  0.00779753 -0.12012073 -0.20995876]
 [ 1.3088279  -0.89726303 -0.12012073  1.85045552  3.23440728]
 [ 2.28769752 -1.56832416 -0.20995876  3.23440728  5.65341363]]


In [14]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c.shape

(2, 3)

In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)